name: Release
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: make build
      - name: Create release ZIP files
        run: |
          cd out
          for filename in *; do
            if [[ -d $filename ]]; then
              mv $filename ${{ github.event.repository.name }}
              zip -rm ${{ github.event.repository.name }}-${{ github.ref_name }}-$filename.zip ${{ github.event.repository.name }}
            fi
          done
      - name: Release on GitHub
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          files: out/*.zip
      - name: Generate signed build provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: out/*.zip
